query {
  viewer {
    repositories(last:10) {
      nodes {
        url
        name
        languages(last:10) {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
